name: CMake on multiple platforms

on: [ push, pull_request ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, windows-latest]
        build_type: [Release]
        c_compiler: [gcc-14, clang-18, cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-24.04
            c_compiler: gcc-14
            cpp_compiler: g++-14
          - os: ubuntu-24.04
            c_compiler: clang-18
            cpp_compiler: clang++-18
        exclude:
          - os: windows-latest
            c_compiler: gcc-14
          - os: windows-latest
            c_compiler: clang-18
          - os: ubuntu-24.04
            c_compiler: cl
    steps:
      - uses: actions/checkout@v4

      - name: Update Linux Packages
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt update && sudo apt upgrade

      - name: Install Latest Compilers
        if: matrix.os == 'ubuntu-24.04'
        run: sudo apt install build-essential gcc-14 g++-14 clang-18 libc++-18-dev libc++abi-18-dev

      - name: Configure CMake
        run: >
          cmake -B "${{ github.workspace }}/build"
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
        run: cmake --build "${{ github.workspace }}/build" --config ${{ matrix.build_type }}

      - name: Test
        working-directory: "${{ github.workspace }}/build"
        run: ./buffalo-test